### ISSUE TITLE
gdlint on godot editor?

### ISSUE THREAD

**Issue by quimnuss** [Scony/godot-gdscript-toolkit#271]
Not an issue but I couldn't find the information anywhere. Is it possible to display the linting hints in the Godot editor? 

It's difficult to correct the linting warnings that gdformat doesn't fix.

Here's my pre-commit

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args: ["--unsafe"] # Instead of loading the files, simply parse them for syntax
      - id: mixed-line-ending
  - repo: https://github.com/Scony/godot-gdscript-toolkit
    rev: 4.2.2
    hooks:
      - id: gdlint
        name: gdlint
        description: "gdlint - linter for GDScript"
        entry: gdlint
        language: python
        language_version: python3
        require_serial: true
        types: [gdscript]
        exclude: ^addons/
      - id: gdformat
        name: gdformat
        description: "gdformat - formatter for GDScript"
        entry: gdformat
        language: python
        language_version: python3
        require_serial: true
        args: ["-l 150"]
        types: [gdscript]
        exclude: ^addons/
```
