### ISSUE TITLE
Missing dependencies in .pre-commit-hooks.yaml

### ISSUE THREAD

**Issue by dementive** [Scony/godot-gdscript-toolkit#317]
To run the linter or formatter with a pre-commit hook the `setuptools` library has to be installed into the pre-commit library. Currently the .pre-commit-hooks.yaml does not do this, updating it to this will fix it:

```yaml
- id: gdlint
  name: gdlint
  description: "gdlint - linter for GDScript"
  entry: gdlint
  language: python
  language_version: python3
  additional_dependencies: [setuptools]
  require_serial: true
  types: [gdscript]
- id: gdformat
  name: gdformat
  description: "gdformat - formatter for GDScript"
  entry: gdformat
  language: python
  language_version: python3
  additional_dependencies: [setuptools]
  require_serial: true
  types: [gdscript]
```
