### ISSUE TITLE
`gdlint` feature: option for Gitlab code quality output format

### ISSUE THREAD

**Issue by OskarUnn** [Scony/godot-gdscript-toolkit#336]
I would like to add a feature to generate [Gitlab code quality](https://docs.gitlab.com/ee/ci/testing/code_quality.html) reports with `gdlint`.

**Example usage in .gitlab-ci.yml**
```
...
gdlint:
  image: python:3.12-alpine
  script:
    - pip3 install "gdtoolkit==4.*"
    - gdlint --format gitlab .
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
...
```

Is this feature suitable for this project?

Perhaps in the future I could add more things related to Gitlab (`.gitlab-ci.yml` example, `gdradon` output to code quality report...)

**Comment by Scony** [comment]
How does adding such a feature to generate gitlab reports work?

**Comment by OskarUnn** [comment]
It would work by saving the found problems to a json file in this format:
```
[
  {
    "description": "'unused' is assigned a value but never used.",
    "check_name": "no-unused-vars",
    "fingerprint": "7815696ecbf1c96e6894b779456d330e",
    "severity": "minor",
    "location": {
      "path": "lib/index.js",
      "lines": {
        "begin": 42
      }
    }
  }
]
```

The problems will show up in Gitlab merge requests like this:
![image](https://github.com/user-attachments/assets/0957287f-4e8f-4785-bb9b-43f29e28f59d)

Here are the changes I made to implement it: https://github.com/OskarUnn/godot-gdscript-toolkit/commit/68d0764160cabe6713a8a837e135817a06e4f7b2

**Comment by GameDev-One** [comment]
I found this capability was also important for my GitLab CI pipeline, so I ended up writing a small Python script to convert the linter’s output into the required format. Script and Gitlab Pipeline Job YAML below:


**ConvertGDLintToGitLabCodeQualJSON.py**
```python
#!/usr/bin/env python3
import json
import hashlib

issues = []
with open("test/lint_comments.txt") as f:
    for line in f:
        # Skip empty lines
        if not line.strip():
            continue

        # Example line format:
        # Game/LevelSelector.gd:10: Error: Max allowed line length (100) exceeded (max-line-length)
        parts = line.split(":", 3)
        if len(parts) < 4:
            continue
        path, line_number, _, rest = parts
        line_number = int(line_number.strip())
        description = rest.strip().replace("Error:", "").strip()

        # Compute a simple fingerprint
        fingerprint_source = f"{path}:{line_number}:{description}"
        fingerprint = hashlib.md5(fingerprint_source.encode("utf-8")).hexdigest()

        issues.append({
            "description": description,
            "fingerprint": fingerprint,
            "severity": "minor",  # or "major" based on rule
            "location": {
                "path": path,
                "lines": {
                    "begin": line_number,
                    "end": line_number
                }
            }
        })

# Write JSON
with open("gl-code-quality.json", "w") as out:
    json.dump(issues, out, indent=2)

```

**.gitlab-ci.yml**
```yaml
# ... Additional workflow rules, stage definitions, and job definitions

linter:
  stage: test
  allow_failure: true
  script:
    - git ls-files '*.gd'
    - cp CICD/.gdlintrc .
    - ls $HOME/.local/bin
    - mkdir -p test
    - EXIT_CODE=0
    - git ls-files '*.gd' -z | grep -z -v '/addons/' | grep -z -v '/script_templates/' | xargs -0 $HOME/.local/bin/gdlint > test/lint_comments.txt 2>&1 || EXIT_CODE=$?
    - python3 CICD/ConvertGDLintToGitLabCodeQualJSON.py
  artifacts:
    paths: 
      - test/
      - gl-code-quality.json
    reports:
      codequality: gl-code-quality.json
# ...
```
