### ISSUE TITLE
Annotation separated from function

### ISSUE THREAD

**Issue by Person-93** [Scony/godot-gdscript-toolkit#375]
This...
```gdscript
@warning_ignore("shadowed_variable")
func _init(id: int, name: String) -> void:
	self.id = id
	self.name = name
```

is reformatted to this:
```gdscript
@warning_ignore("shadowed_variable")


func _init(id: int, name: String) -> void:
	self.id = id
	self.name = name
```

**Comment by onyxwizard** [comment]
If you are using GDScript-specific formatter **`gdformat`**  check for its configuration file `.gdformat` ensure it preserves the adjacency of annotations.
For instance,try 

```yaml
blank_lines:
  before_functions: 0  # Disable blank lines before all functions
```

**Comment by Person-93** [comment]
> If you are using GDScript-specific formatter **`gdformat`** check for its configuration file `.gdformat` ensure it preserves the adjacency of annotations. For instance,try
> 
> blank_lines:
>   before_functions: 0  # Disable blank lines before all functions

I don't want to disable blank lines before functions in all cases. I just want the annotation to stay with the thing that it's annotating.

**Comment by onyxwizard** [comment]
Here is a script that might solve your problem. In `.gdformat` config to  keep annotations (e.g., @warning_ignore) and  still allowing blank lines before functions without annotations.
```yaml
blank_lines:
  before_functions: 1  # Insert 1 blank line before functions without annotations
  before_annotated_functions: 0  # No blank lines before functions with annotations
annotations:
  preserve_adjacency: true  # Treat annotations as part of the function
  spacing_after: 0  # No blank lines after annotations
```
